"""empty message

Revision ID: 981e9f89a1d7
Revises: eca4e0d6f322
Create Date: 2022-06-24 11:43:08.312094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981e9f89a1d7'
down_revision = 'eca4e0d6f322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggest_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggests', schema=None) as batch_op:
        batch_op.drop_column('suggest_time')

    # ### end Alembic commands ###
