"""empty message

Revision ID: dc652354025c
Revises: a9b9c328e441
Create Date: 2022-06-23 15:47:36.164352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc652354025c'
down_revision = 'a9b9c328e441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('userid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('movieid',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('movieid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('userid',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
